config/routes.rb
Rails.application.routes.draw do
  # get '/bookings/new', to: 'bookings#new'
  # post '/bookings', to: 'bookings#create'
  get '/my_bookings', to: 'bookings#my_bookings'
  get '/bookings/:id', to: 'bookings#show', as: 'booking'
  get '/requested_spells', to: 'bookings#requested_spells'
  delete '/bookings/:id', to: 'bookings#destroy', as: 'cancel_booking'

  resources :spells, only: %i[index new create show] do
    resources :bookings, only: %i[new create]
  end

  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get '/spells', to: 'spells#index'
  # get '/spells/new', to: 'spells#new'
  # post '/spells', to: 'spells#create'
  # get '/spells/:id', to: 'spells#show', as: 'spell'
  get '/my_spells', to: 'spells#my_spells'
  get '/bookings/:id/accepted', to: 'bookings#accepted', as: 'accept_booking'
  get '/bookings/:id/declined', to: 'bookings#declined', as: 'decline_booking'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :spell

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :end_date, comparison: { greater_than: :start_date }
end

app/models/spell.rb
class Spell < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo

  validates :name, presence: true
  validates :category, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :price, presence: true
  validates :user, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_category_location_name_and_description,
                  against: %i[category location description name],
                  using: {
                    tsearch: { prefix: true } # <-- now `superman batm` will return something!
                  }
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :spells, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :spell_bookings, through: :spells, source: :bookings
  validates :first_name, :last_name, :address, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # fixes "Can't verify CSRF token authenticity" error
  protect_from_forgery with: :null_session,
      if: Proc.new { |c| c.request.format =~ %r{application/json} }

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :email])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :email])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
    @spell = Spell.find(@booking.spell_id)
  end

  def new
    @booking = Booking.new
    @spell = Spell.find(params[:spell_id])
  end

  def requested_spells
    @bookings = current_user.spell_bookings
  end

  def create
    @booking = Booking.new(booking_params)
    @spell = Spell.find(params[:spell_id])
    @booking.user = current_user
    @booking.spell_id = params[:spell_id]
    if @booking.save
      redirect_to my_bookings_path, notice: "Your booking is created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def my_bookings
    @bookings = Booking.where(user_id: current_user)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to booking_path, status: :see_other
  end

  def accepted
    @booking = Booking.find(params[:id])
    @booking.status = "Accepted"
    @booking.save
    redirect_to requested_spells_path
  end

  def declined
    @booking = Booking.find(params[:id])
    @booking.status = "Declined"
    @booking.save
    redirect_to requested_spells_path
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :start_date, :end_date, :spell_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @spells = Spell.all

    @background_img = [
      'https://res.cloudinary.com/dppymdnxh/image/upload/v1668616924/spell%20images/vera-velichko-potions-poison-skull-wallpaper_vornxb.jpg',
      'https://res.cloudinary.com/dppymdnxh/image/upload/v1668617000/spell%20images/2306148a6826c3849554ff6e82f358c0_tm8orh.jpg',
      'https://res.cloudinary.com/dppymdnxh/image/upload/v1668616976/spell%20images/bdf4e8e60c1fedae47811e60754532c1_hnmf8b.png'
    ]
    @user_img = [
      'https://res.cloudinary.com/dppymdnxh/image/upload/v1668617351/spell%20images/users/09-angela_wj9jud.jpg',
      'https://res.cloudinary.com/dppymdnxh/image/upload/v1668617350/spell%20images/users/01-dimitri_gjcpcp.jpg', 'https://res.cloudinary.com/dppymdnxh/image/upload/v1668617350/spell%20images/users/02-tanya_ilefnh.jpg',
      'https://res.cloudinary.com/dppymdnxh/image/upload/v1668617350/spell%20images/users/08-patt_rffvlp.jpg',
      'https://res.cloudinary.com/dppymdnxh/image/upload/v1668617350/spell%20images/users/03-steve_uaz0jx.jpg'
    ]
  end
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  before_action :images, only: %i[index my_spells show]
  def index
    if params[:query].present?
      @spells = Spell.search_by_category_location_name_and_description(params[:query])
      # @spells = Spell.all
      # images
      markers
    else
      @spells = Spell.all
      images
      markers
    end
  end

  def my_spells
    @spells = Spell.where(user_id: current_user)
  end

  def new
    @spell = Spell.new
  end

  def show
    @spell = Spell.find(params[:id])
  end

  def create
    @spell = Spell.new(spell_params)
    @spell.user = current_user
    if @spell.save
      redirect_to spell_path(@spell), notice: "Your spell was created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def markers
    @markers = @spells.geocoded.map do |spell|
      {
        lat: spell.latitude,
        lng: spell.longitude,
        info_window: render_to_string(partial: "info_window", locals: { spell: }),
        image_url: helpers.asset_url("location.png")
      }
    end
  end

  private

  def spell_params
    params.require(:spell).permit(:name, :category, :description, :location, :price, :photo)
  end

  def images
    @background_img = [
      'https://res.cloudinary.com/dppymdnxh/image/upload/v1668616924/spell%20images/vera-velichko-potions-poison-skull-wallpaper_vornxb.jpg',
      'https://res.cloudinary.com/dppymdnxh/image/upload/v1668617000/spell%20images/2306148a6826c3849554ff6e82f358c0_tm8orh.jpg',
      'https://res.cloudinary.com/dppymdnxh/image/upload/v1668616976/spell%20images/bdf4e8e60c1fedae47811e60754532c1_hnmf8b.png'
    ]

    @user_img = [
      'https://res.cloudinary.com/dppymdnxh/image/upload/v1668617351/spell%20images/users/09-angela_wj9jud.jpg',
      'https://res.cloudinary.com/dppymdnxh/image/upload/v1668617350/spell%20images/users/01-dimitri_gjcpcp.jpg', 'https://res.cloudinary.com/dppymdnxh/image/upload/v1668617350/spell%20images/users/02-tanya_ilefnh.jpg',
      'https://res.cloudinary.com/dppymdnxh/image/upload/v1668617350/spell%20images/users/08-patt_rffvlp.jpg',
      'https://res.cloudinary.com/dppymdnxh/image/upload/v1668617350/spell%20images/users/03-steve_uaz0jx.jpg'
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for([@spell, @booking]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :start_date, html5: true %>
    <%= f.input :end_date, html5: true %>
  </div>
  
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/my_bookings.html.erb
<div class="container-wrapper">
<div class="container container-request">

<h1 class="requested-font">MY BOOKINGS</h1>

  <% @bookings.each do |booking| %>
    <div class="notification">
      <%= image_tag "https://res.cloudinary.com/dppymdnxh/image/upload/v1668616924/spell%20images/vera-velichko-potions-poison-skull-wallpaper_vornxb.jpg", height:60, weight:60 %>
      <div class="notification-content">
        <p><small><%= booking.start_date %> to  <%= booking.end_date %></small></p>
        <p><%= booking.spell.name %></p>
        <p><%= booking.spell.price %>$/day</p>
        <p><strong><%= booking.status %></strong></p>
      </div>

      <div class="notification-actions">
        <%= link_to "Cancel", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      </div>
    </div>
  <% end %>

  </div>
</div>

app/views/bookings/new.html.erb
<div class="new_spell__container">

 <div class="form_wrapper">
  <div class="curvy banner_curve--mod ">
      <svg class="witch__svg" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
        <path d="M0,0V46.29c47.79,22.2,103.59,32.17,158,28,70.36-5.37,136.33-33.31,206.8-37.5C438.64,32.43,512.34,53.67,583,72.05c69.27,18,138.3,24.88,209.4,13.08,36.15-6,69.85-17.84,104.45-29.34C989.49,25,1113-14.29,1200,52.47V0Z" opacity=".25" class="shape-fill"></path>
        <path d="M0,0V15.81C13,36.92,27.64,56.86,47.69,72.05,99.41,111.27,165,111,224.58,91.58c31.15-10.15,60.09-26.07,89.67-39.8,40.92-19,84.73-46,130.83-49.67,36.26-2.85,70.9,9.42,98.6,31.56,31.77,25.39,62.32,62,103.63,73,40.44,10.79,81.35-6.69,119.13-24.28s75.16-39,116.92-43.05c59.73-5.85,113.28,22.88,168.9,38.84,30.2,8.66,59,6.17,87.09-7.5,22.43-10.89,48-26.93,60.65-49.24V0Z" opacity=".5" class="shape-fills"></path>
        <path d="M0,0V5.63C149.93,59,314.09,71.32,475.83,42.57c43-7.64,84.23-20.12,127.61-26.46,59-8.63,112.48,12.24,165.56,35.4C827.93,77.22,886,95.24,951.2,90c86.53-7,172.46-45.71,248.8-84.81V0Z" class="shape-fills"></path>
      </svg>
    </div>

    <h1 class='index_title'>CREATE A BOOKING</h1>
    <div>
      <%= render "form", booking: @booking %>
    </div>

     <div class="">
      <%= image_tag 'witch.svg', class: 'hero-image' %>
    </div>

    <%= link_to my_bookings_path, class: 'back-btn' do %>
    <p><%= icon('fa', 'circle-arrow-left')%> All bookings</p>
    <% end %>

 </div>
</div>

app/views/bookings/requested_spells.html.erb
<div class="container-wrapper">
<div class="container container-request">
  <h1 class="requested-font">MY RESQUEST SPELLS</h1>

  <% @bookings.each do |booking| %>
    <div class="notification" data-controller="bookings">
      <%= image_tag "https://res.cloudinary.com/dppymdnxh/image/upload/v1668616924/spell%20images/vera-velichko-potions-poison-skull-wallpaper_vornxb.jpg", height:60, weight:60 %>
      <div class="notification-content">
        <p><small><%= booking.start_date %> to  <%= booking.end_date %></small></p>
        <p><%= booking.spell.name %></p>
        <p><strong><%= booking.status %></strong></p>
      </div>

      <div class="notification-actions">
      <%= link_to "Accept", accept_booking_path(booking)%>
      <%= link_to "Decline", decline_booking_path(booking)%>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<h2>Spell: <%= link_to @booking.spell.name, spell_path(@spell) %></h2>
<h4>Booking Status: <%= @booking.status %></h4>
<p>Starting date: <%= @booking.start_date %></p>
<p>Ending date: <%= @booking.end_date%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>THELastResort</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner_wrapper">
  <div class="banner">
    <div class="banner_text_box">
      <h1>ANYWHERE, ANYWEEK<br> Grab A Spell Today!</h1>
      <p> Normal witches get stuck in traffic.</p>
      <p> We Work Fully Remote.</p>

      <div class='banner_text_box_btn'>
        <%= link_to 'Choose Your Spell Below', spells_path, class: 'banner_text_box_btn_link' %>
      </div>
    </div>
    <div class="hero-images">
      <%= image_tag 'witch.svg', class: 'hero-image' %>

    </div>
    <div class="banner_curve">
      <svg class="witch__svg" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
        <path d="M0,0V46.29c47.79,22.2,103.59,32.17,158,28,70.36-5.37,136.33-33.31,206.8-37.5C438.64,32.43,512.34,53.67,583,72.05c69.27,18,138.3,24.88,209.4,13.08,36.15-6,69.85-17.84,104.45-29.34C989.49,25,1113-14.29,1200,52.47V0Z" opacity=".25" class="shape-fill"></path>
        <path d="M0,0V15.81C13,36.92,27.64,56.86,47.69,72.05,99.41,111.27,165,111,224.58,91.58c31.15-10.15,60.09-26.07,89.67-39.8,40.92-19,84.73-46,130.83-49.67,36.26-2.85,70.9,9.42,98.6,31.56,31.77,25.39,62.32,62,103.63,73,40.44,10.79,81.35-6.69,119.13-24.28s75.16-39,116.92-43.05c59.73-5.85,113.28,22.88,168.9,38.84,30.2,8.66,59,6.17,87.09-7.5,22.43-10.89,48-26.93,60.65-49.24V0Z" opacity=".5" class="shape-fill"></path>
        <path d="M0,0V5.63C149.93,59,314.09,71.32,475.83,42.57c43-7.64,84.23-20.12,127.61-26.46,59-8.63,112.48,12.24,165.56,35.4C827.93,77.22,886,95.24,951.2,90c86.53-7,172.46-45.71,248.8-84.81V0Z" class="shape-fill"></path>
      </svg>
    </div>
  </div>
</div>

<div class="card-section">
      <ul class="cards margin-zero padding-bot-80px padding_top-80px">
      <div class="cards__wrapper_resize margin-zero">
        <% @spells.each do |spell| %>
          <li class="card__Separate">
          <%= link_to spell_path(spell) do %>
              <div class="card-trip">

                <% if spell.photo.attached? %>
                  <%= cl_image_tag spell.photo.key, class: 'show__img border-r' %>
                <% end  %>

                <% if spell.photo.attached? == false %>
                  <%= image_tag @background_img.sample %>
                <% end  %>

                <div class="card-trip-infos">
                  <div>
                    <h2><%= spell.name.capitalize %></h2>
                    <p><%= spell.location.capitalize %></p>
                  </div>
                  <h2 class="card-trip-pricing price">$<%= spell.price%></h2>
                  <%= image_tag @user_img.sample, class: 'card-trip-user avatar-bordered' %>
                </div>
              </div>
          <% end %>
            </li>
        <% end %>
        </div>
      </ul>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer__addr">
    <h1 class="footer__logo">Last Resort</h1>

    <h2>Contact</h2>
    <address> Plateau Mont-Royal<br>
      <a class="footer__btn" href="mailto:example@gmail.com">Email Us</a>
    </address>
  </div>

  <ul class="footer__nav">
    <li class="nav__item">
      <h2 class="nav__title">Media</h2>

      <ul class="nav__ul nav_social">
        <li><a href="#"><i class="fab fa-github"></i></a></li>
        <li><a href="#"><i class="fab fa-instagram"></i></a></li>
        <li><a href="#"><i class="fab fa-facebook"></i></a></li>
      </ul>
    </li>

    <li class="nav__item nav__item--extra">
      <h2 class="nav__title">Services</h2>

      <ul class="nav__ul nav__ul--extra">
        <li><a href="#">Home</a></li>
        <li><a href="#">Create a Spell</a></li>
        <li><a href="#">My Spells</a></li>
        <li><a href="#">My Bookings</a></li>
      </ul>
    </li>

    <li class="nav__item">
      <h2 class="nav__title">Legal</h2>

      <ul class="nav__ul">
        <li><a href="#">Privacy Policy</a></li>
        <li><a href="#">Terms of Use</a></li>
        <li><a href="#">Sitemap</a></li>
      </ul>
    </li>
  </ul>

  <div class="legal">
    <p>&copy; 2022 Something. All rights reserved.</p>

    <div class="legal__links">
      <span>Made with <span class="heart">♥</span></span>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav>
  <div class="navbar navbar-expand-sm navbar-light navbar-lastresort">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <%= image_tag ("last-resort.png") %>
    </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

   <div class ="container-nav">
      <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
        </li>
          <li class="nav-item"><%= link_to "Home", root_path, class:"nav-link" %></li>
          <li class="nav-item"><%= link_to "All Spells", spells_path, class:"nav-link" %></li>
          <li class="nav-item"><%= link_to "Create a Spell", new_spell_path, class:"nav-link" %></li>
          <li class="nav-item"><%= link_to "My Spells", my_spells_path, class:"nav-link" %></li>
          <li class="nav-item"><%= link_to "My Bookings", my_bookings_path, class:"nav-link" %></li>
          <li class="nav-item"><%= link_to "Requests", requested_spells_path, class:"nav-link" %></li>
        </ul>
      </div>

      <div class="search">
            <%= form_with url: spells_path, method: :get, class: "d-flex my-3" do %>
              <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Find a spell"
              %>
              <%= submit_tag "Search", class: "btn my-2 my-sm-0 btn btn-primary" %>
            <% end %>
      </div>
    </div>
        <%# <form class="form-inline">
          <input class="form-control mr-sm-2" type="search" placeholder="Search.." aria-label="Search">
          <button class="btn my-2 my-sm-0" type="submit">Submit</button>
        </form> %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <div class="nav-margin">
            <li class="nav-item border">
              <%= link_to "Register", new_user_registration_path, class:"nav-link-register" %>
            </li>
          </div>
          <div class="nav-margin">
            <li class="nav-item border">
              <%= link_to "Sign in", new_user_session_path, class:"nav-link-register" %>
            </li>
          </div>
        <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "My Spells", my_spells_path, class:"dropdown-item" %>
                <%= link_to "My Booking", my_bookings_path, class:"dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
        </li>
        <!--li class="nav-item"-->
        <!--/li-->
      </ul>
    </div>
  </div>
</nav>

app/views/spells/_form.html.erb
<%= simple_form_for(@spell) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :category, collection: ['Home', 'Self', 'Love', 'Social', 'Family', 'Career'] %>
    <%= f.input :location,
      input_html: {data: {location_autocomplete_target: "location"}},
      wrapper_html: {data: {controller: "location-autocomplete", location_autocomplete_api_key_value: ENV["MAPBOX_API"]}}
    %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions ">
    <%= f.button :submit, class: 'form__submit' %>
  </div>
<% end %>

app/views/spells/_info_window.html.erb
<div class="container">
  <h2><%= spell.name %></h2>
  <p><%= spell.location %></p>
  <p><%= spell.description %></p>
  <p><%= spell.price %>$</p>
</div>

app/views/spells/my_spells.erb
<h1 class='index_title'>My Spells</h1>
<% @spells.map do |spell| %>
  <div class="height_auto show__container">
    <div class="show_wrapper">
      <div class="show__text">
        <h2 class='show_text_h2'>
          <%= spell.name.capitalize %>
        </h2>
        <div class="show__text_box">
          <div class="desc__box">
            <p class="desc">Description:</p>
            <p><%= spell.description.capitalize %></p>
          </div>
          <div>
            <p class="category_location">
              <span><span class="desc">Category:</span> <%= spell.category.capitalize %></span> <span><span class="desc">Location:</span> <%= spell.location.capitalize %></span>
            </p>
          </div>
        </div>
        <p class= 'show-price'>Price: <span>$<%= spell.price%></span></p>
      </div>
      <div>
        <% if spell.photo.attached? %>
          <%= cl_image_tag spell.photo.key, class: 'show__img' %>
        <% end  %>
        <% if spell.photo.attached? == false %>
          <%= image_tag @background_img.sample, class: 'show__img' %>
        <% end  %>
      </div>
    </div>
  </div>
<% end %>

app/views/spells/new.html.erb
<div class="new_spell__container">

 <div class="form_wrapper">
  <div class="curvy banner_curve--mod ">
      <svg class="witch__svg" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
        <path d="M0,0V46.29c47.79,22.2,103.59,32.17,158,28,70.36-5.37,136.33-33.31,206.8-37.5C438.64,32.43,512.34,53.67,583,72.05c69.27,18,138.3,24.88,209.4,13.08,36.15-6,69.85-17.84,104.45-29.34C989.49,25,1113-14.29,1200,52.47V0Z" opacity=".25" class="shape-fill"></path>
        <path d="M0,0V15.81C13,36.92,27.64,56.86,47.69,72.05,99.41,111.27,165,111,224.58,91.58c31.15-10.15,60.09-26.07,89.67-39.8,40.92-19,84.73-46,130.83-49.67,36.26-2.85,70.9,9.42,98.6,31.56,31.77,25.39,62.32,62,103.63,73,40.44,10.79,81.35-6.69,119.13-24.28s75.16-39,116.92-43.05c59.73-5.85,113.28,22.88,168.9,38.84,30.2,8.66,59,6.17,87.09-7.5,22.43-10.89,48-26.93,60.65-49.24V0Z" opacity=".5" class="shape-fills"></path>
        <path d="M0,0V5.63C149.93,59,314.09,71.32,475.83,42.57c43-7.64,84.23-20.12,127.61-26.46,59-8.63,112.48,12.24,165.56,35.4C827.93,77.22,886,95.24,951.2,90c86.53-7,172.46-45.71,248.8-84.81V0Z" class="shape-fills"></path>
      </svg>
    </div>

    <h1 class='index_title'>CREATE A SPELL</h1>
    <div>
      <%= render "form", spell: @spell %>
    </div>

     <div class="">
      <%= image_tag 'witch.svg', class: 'hero-image' %>
    </div>

    <%= link_to spells_path, class: 'back-btn' do %>
    <p><%= icon('fa', 'circle-arrow-left')%>  Back to spells</p>
    <% end %>

 </div>
</div>

app/views/spells/show.html.erb
<div class="height_70 show__container ">
  <div class="show_wrapper">
    <div class="show__text">
      <h2 class='show_text_h2'>
        <%= @spell.name.capitalize %>
        <p class="spell__first_name">By <%= @spell.user.first_name.capitalize%></p>
      </h2>
      <div class="show__text_box">

      <div class="desc__box">
        <p class="desc">Description:</p>
        <p><%= @spell.description.capitalize %></p>
      </div>
        <div>
          <p class="category_location">
            <span><span class="desc">Category:</span> <%= @spell.category.capitalize %></span> <span><span class="desc">Location:</span> <%= @spell.location.capitalize%></span>
          </p>
        </div>
      </div>
      <p class= 'show-price'>Price: <span>$<%= @spell.price%></span></p>
      <div class="flex__link">
        <%= link_to new_spell_booking_path(@spell) do %>
          <h2 class="nav-link-register booking_link"> Book <%= @spell.name.capitalize %></h2>
        <% end %>
      </div>
    </div>
    <div class="show__img_box">
      <% if @spell.photo.attached? %>
        <%= cl_image_tag @spell.photo.key, class: 'show__img' %>
      <% end  %>
      <% if @spell.photo.attached? == false %>
        <%= image_tag @background_img.sample, class: 'show__img' %>
      <% end  %>
    </div>
  </div>
</div>